### ISSUE TITLE
.NET 3.1.14/SDK 3.1.408 support

### ISSUE THREAD

**Issue by MagicAndre1981** [pjgpetecodes/dotnetcore3pi#3]
I've installed .Net 3.1 with your script and it uses an old .net core 3.1 SDK/Version:

```
pi@raspberrypi:~ $ dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.202
 Commit:    db7cc87d51

Laufzeitumgebung:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /opt/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.404 [/opt/dotnet/sdk]
  5.0.202 [/opt/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
pi@raspberrypi:~ $ 
```

Can you please support the latest version? And how does update work? run the script again?

**Comment by pjgpetecodes** [comment]
Hey @MagicAndre1981 ... Thanks for raising the issue.. I've updated the script to the latest version...

You can update by running the script again, it will automatically pull down the latest verison.

THanks!

**Comment by MagicAndre1981** [comment]
works. Btw, do I have to manually cleanup the old runtime sdk files? I still see the 404 SDK and the 3.1.10 files

**Comment by pjgpetecodes** [comment]
That's great...

I tend to just leave the old files there too be fair...

But, you can go to /opt/dotnet/sdk and delete the folders of old versions using the rm -rf command if you like...

Cheers!
